# Generated by Django 6.1.1 on 2026-09-29 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Kategori Slug')),
                ('icon', models.CharField(default='HelpCircle', max_length=50, verbose_name='Lucide İkon Adı')),
                ('color_theme', models.CharField(default='cyan', max_length=50, verbose_name='Renk Teması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='Kod veya Formül Parçacığı')),
                ('points', models.IntegerField(default=10, verbose_name='Puan Değeri')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_api.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Şık Metni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru Şık mı?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_api.question', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Şık',
                'verbose_name_plural': 'Şıklar',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50, verbose_name='Oyuncu Adı')),
                ('total_score', models.IntegerField(default=0, verbose_name='Toplam Skor')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('empty_count', models.IntegerField(default=0, verbose_name='Boş Sayısı')),
                ('total_time_taken', models.FloatField(default=0.0, verbose_name='Toplam Süre (sn)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz_api.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Skor Kaydı',
                'verbose_name_plural': 'Skor Kayıtları',
                'ordering': ['-total_score', 'total_time_taken', '-created_at'],
            },
        ),
    ]
