# Generated by Django 6.1.1 on 2026-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='music_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Müzik Başlığı'),
        ),
        migrations.AddField(
            model_name='category',
            name='music_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Arka Plan Müziği URL'si"),
        ),
    ]
